# Website details
name: CK Coding Odyssey
description: Going from Lawyer to Programmer
email: codi.kraus@gmail.com
author: Codi Kraus
lang: en
locale: en_US

# Jekyll
paginate: 10
highlighter: rouge
markdown: kramdown
plugins: [jekyll-paginate]
timezone: America/Chicago
paginateLabel: page
paginate_path: "page/:num"
permalink: /:categories/:year/:month/:day/:title
baseurl: https://ph3nomforko.github.io
github_username: ph3nomforko

# Includes
addthisId: ""
disqusUsername: ""
googleAnalyticsId: ""

# Search engine verifications
bing: ""
yandex: ""
google: ""

# Sitemap
sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/404.html"
  include_posts:
    - "/index.html"
  change_frequency_name: "daily"
  priority_name: "1.00"

gems: [jekyll-paginate, jekyll-feed]
